spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_aws_rest
    username: root
    password: admroot123
    
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
      show-sql: false